### PR TITLE
Workaround for Groupbox widget sometimes finding the incorrect siblings

### PR DESCRIPTION
**Pull request by Maismaus**
I noticed that since the MX8 upgrade, the widget sometimes found a <SCRIPT> tag which it appended to the groupbox header. I haven't been able to find the exact cause for this behaviour, but I nevertheless added a workaround to find another sibling if a SCRIPT tag is found initially. 
This fixes issues for some Mendix 8 projects using the widget. 

I also added the default Mendix boilerplate functionality in order to work on the widget.

### CODE REVIEW

**Comment by mgroeneweg** [comment]
Today I submitted the replacement widget to the appstore. I'm sorry for the effort you put in here but I will deprecate the widget as soon as the new widget is approved.

**Comment by Maismaus** [comment]
Hey Marcel, no problem at all! Great to hear you're working on a replacement widget.

**Comment by Maismaus** [comment]
@mgroeneweg , any idea when the new widget will become available? Can we track it somewhere?

**Comment by mgroeneweg** [comment]
I hope in the next few days. It is waiting for appstore approval.

**Comment by mgroeneweg** [comment]
Available now: [https://marketplace.mendix.com/link/component/117097](https://marketplace.mendix.com/link/component/117097)

**Pull request closed without merging**
